--------------------------------------------------------
--  File created - niedziela-czerwca-09-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence REZERWACJE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "AKAWCZ4"."REZERWACJE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ATRAKCJE
--------------------------------------------------------

  CREATE TABLE "AKAWCZ4"."ATRAKCJE" 
   (	"ID" NUMBER(*,0), 
	"NAZWA" VARCHAR2(30 BYTE), 
	"OPIS" VARCHAR2(500 BYTE), 
	"LINK" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRACOWNICY
--------------------------------------------------------

  CREATE TABLE "AKAWCZ4"."PRACOWNICY" 
   (	"ID_PRACOWNIKA" NUMBER(*,0), 
	"IMIE" VARCHAR2(20 BYTE), 
	"NAZWISKO" VARCHAR2(50 BYTE), 
	"PESEL" NUMBER(11,0), 
	"PENSJA" NUMBER, 
	"PRACA_DZIS" VARCHAR2(3 BYTE), 
	"ID_PRZYPISANEJ_ATRAKCJI" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REZERWACJE
--------------------------------------------------------

  CREATE TABLE "AKAWCZ4"."REZERWACJE" 
   (	"ID" NUMBER, 
	"IMIE" VARCHAR2(20 BYTE), 
	"NAZWISKO" VARCHAR2(50 BYTE), 
	"ILOSCBILETOW" NUMBER(*,0), 
	"KWOTA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into AKAWCZ4.ATRAKCJE
SET DEFINE OFF;
Insert into AKAWCZ4.ATRAKCJE (ID,NAZWA,OPIS,LINK) values ('1','Splash','Idealna na letnie gor¹ce dni. Podczas sp³ywu tratw¹ na pewno nie zabraknie poczucia œwie¿ej bryzy!','https://seaworld.com/orlando/-/media/migrated-media/seaworld-orlando/images/rides/journey-to-atlantis/750x422_swo_rides_journeytoatlantis_media_3.png?h=422&w=750&la=en&hash=41BA1A9963A689FE1DC21F03F122C95D');
Insert into AKAWCZ4.ATRAKCJE (ID,NAZWA,OPIS,LINK) values ('2','Superior','Najwy¿sza i najszybsza kolejka górska typu mega coaster w Europie o wysokoœci 80 m, pierwszym spadku pod k¹tem 85 stopni! Wra¿enie robi równie¿ prêdkoœæ maksymalna - 150 km/h!','https://energylandia.pl/wp-content/uploads/2018/03/hyperion_2024_10-900x600.jpg');
Insert into AKAWCZ4.ATRAKCJE (ID,NAZWA,OPIS,LINK) values ('3','Samoloty','Samoloty jak sama nazwa wskazuje jest kolejk¹ widokow¹, pozwalaj¹c¹ na spokojn¹ przeja¿d¿kê dooko³a strefy dla najm³odszych.','https://energylandia.pl/wp-content/uploads/2017/02/samoloty_2024_1-900x600.jpg');
Insert into AKAWCZ4.ATRAKCJE (ID,NAZWA,OPIS,LINK) values ('4','Layan','Rollercoaster zapewni goœciom potê¿ny zastrzyk adrenaliny. Przejazd podniesie ciœnienie nawet najbardziej doœwiadczonym bywalcom parków rozrywki.','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzWsl8qNb964-rUsF5esRfNZhKsy4sNprs3g&s');
Insert into AKAWCZ4.ATRAKCJE (ID,NAZWA,OPIS,LINK) values ('5','Water Bomb','Atrakcja otwarta w okresie 01.4 - 31.10.  To najwiêksza i najszybsza tego rodzaju wodna atrakcja w naszym obiekcie, której nie mo¿na pomin¹æ. ','https://www.gannett-cdn.com/presto/2022/05/18/USAT/2a28facb-03d4-4a00-a005-496ffc98cc87-GettyImages-1051015264.jpg?width=592&format=pjpg&auto=webp&quality=70');
Insert into AKAWCZ4.ATRAKCJE (ID,NAZWA,OPIS,LINK) values ('6','F1','Wsi¹dŸ w kolejke wzorowan¹ formu³¹ 1 i poczuj prawdziw¹ prêdkoœæ!','https://ewawemiratach.wordpress.com/wp-content/uploads/2014/03/wpid-ferrari-world-9255b2255d.jpg?w=604');
REM INSERTING into AKAWCZ4.PRACOWNICY
SET DEFINE OFF;
Insert into AKAWCZ4.PRACOWNICY (ID_PRACOWNIKA,IMIE,NAZWISKO,PESEL,PENSJA,PRACA_DZIS,ID_PRZYPISANEJ_ATRAKCJI) values ('1','Kamil','Œlimak','99799799799','7500','NIE','4');
Insert into AKAWCZ4.PRACOWNICY (ID_PRACOWNIKA,IMIE,NAZWISKO,PESEL,PENSJA,PRACA_DZIS,ID_PRZYPISANEJ_ATRAKCJI) values ('3','Marysia','Kowalska','12233344445','10000','TAK','1');
Insert into AKAWCZ4.PRACOWNICY (ID_PRACOWNIKA,IMIE,NAZWISKO,PESEL,PENSJA,PRACA_DZIS,ID_PRZYPISANEJ_ATRAKCJI) values ('5','Rafa³','Ptak','54444333221','8900','TAK','2');
Insert into AKAWCZ4.PRACOWNICY (ID_PRACOWNIKA,IMIE,NAZWISKO,PESEL,PENSJA,PRACA_DZIS,ID_PRZYPISANEJ_ATRAKCJI) values ('19','Pawe³ ','Paw','80112678913','5250','TAK','1');
Insert into AKAWCZ4.PRACOWNICY (ID_PRACOWNIKA,IMIE,NAZWISKO,PESEL,PENSJA,PRACA_DZIS,ID_PRZYPISANEJ_ATRAKCJI) values ('10','Darek','Samotnik','86562847162','9999','NIE','3');
REM INSERTING into AKAWCZ4.REZERWACJE
SET DEFINE OFF;
Insert into AKAWCZ4.REZERWACJE (ID,IMIE,NAZWISKO,ILOSCBILETOW,KWOTA) values ('1','Jan',' Kowalski','3','250');
Insert into AKAWCZ4.REZERWACJE (ID,IMIE,NAZWISKO,ILOSCBILETOW,KWOTA) values ('2','Maria','Kot','1','50');
Insert into AKAWCZ4.REZERWACJE (ID,IMIE,NAZWISKO,ILOSCBILETOW,KWOTA) values ('3','Józef','Wariat','2','100');
--------------------------------------------------------
--  DDL for Index ATRAKCJE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AKAWCZ4"."ATRAKCJE_PK" ON "AKAWCZ4"."ATRAKCJE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRACOWNICY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AKAWCZ4"."PRACOWNICY_PK" ON "AKAWCZ4"."PRACOWNICY" ("ID_PRACOWNIKA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REZERWACJE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AKAWCZ4"."REZERWACJE_PK" ON "AKAWCZ4"."REZERWACJE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger REZERWACJE_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "AKAWCZ4"."REZERWACJE_TRG" 
BEFORE INSERT ON REZERWACJE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT REZERWACJE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AKAWCZ4"."REZERWACJE_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table PRACOWNICY
--------------------------------------------------------

  ALTER TABLE "AKAWCZ4"."PRACOWNICY" MODIFY ("ID_PRACOWNIKA" NOT NULL ENABLE);
  ALTER TABLE "AKAWCZ4"."PRACOWNICY" MODIFY ("IMIE" NOT NULL ENABLE);
  ALTER TABLE "AKAWCZ4"."PRACOWNICY" MODIFY ("NAZWISKO" NOT NULL ENABLE);
  ALTER TABLE "AKAWCZ4"."PRACOWNICY" MODIFY ("PESEL" NOT NULL ENABLE);
  ALTER TABLE "AKAWCZ4"."PRACOWNICY" MODIFY ("PENSJA" NOT NULL ENABLE);
  ALTER TABLE "AKAWCZ4"."PRACOWNICY" MODIFY ("PRACA_DZIS" NOT NULL ENABLE);
  ALTER TABLE "AKAWCZ4"."PRACOWNICY" MODIFY ("ID_PRZYPISANEJ_ATRAKCJI" NOT NULL ENABLE);
  ALTER TABLE "AKAWCZ4"."PRACOWNICY" ADD CONSTRAINT "PRACOWNICY_PK" PRIMARY KEY ("ID_PRACOWNIKA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ATRAKCJE
--------------------------------------------------------

  ALTER TABLE "AKAWCZ4"."ATRAKCJE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "AKAWCZ4"."ATRAKCJE" ADD CONSTRAINT "ATRAKCJE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REZERWACJE
--------------------------------------------------------

  ALTER TABLE "AKAWCZ4"."REZERWACJE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "AKAWCZ4"."REZERWACJE" ADD CONSTRAINT "REZERWACJE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
